---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-app-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCyXESqKUN7Iqd63ikkGfQKDVq/aX4x8+pfx1kqA4VkH9oH7obuDTPocNWWncBDY8ZCRjWTJVLc7qFkHlPAPl3s5x+59H6SAtj/qFDww7kAhTheO2D7JJVPWeXcXznOm2HmGQ7zj1SsTNs0KV2vWyI9d4s4fmCOOzz9minHkaG8KunL+33nweZEVX/irpLrscJXNwERZxNxyc8nKCkermcGMuIzX0nM8ZD0Nv7BDmOfteC+fjWC7bF6OmTmfC7I8u16Xk23tO/KXLyCMDnep6JsfRg2/zZtgyAoZR9c4gC+Rf6WyLt60t9XTLQtZSauwzjtpM5Xa7vISrv4VZkPg019c0sQZt0PhTVNG9xcXpW+VbJ2BB2V2tjrzkGyW3IrDbAT7Sk9wzALDybVBK6BjIFITqEI2aaNvo2JAhFxjiqArmu+9MTZzRqpg4/q0+m5/Hdecz+GA0O/U+QPDR70iM6473o2cay1XXeOfPFI/71eMCJd0HFBWg+2BLKF+BOIzTcZ3O75napQivubcLf6Z1RsPZdZ2JneO+5AK/K/lMlbdc48Wscv0ZDsetMhHwiTqoy/rdtOLMcfwXq1po22bYEaYQ4szVrG3qR7k6zSGYZEaKIJDfm3ODQUPj0Fg8YiEhUn2H/5tLFSKkLS7s8PK9JOOiIvaPU0f+/uQfhUmsk/sgGi7jvClJFst6IcRUhZfASK4sGWw7J8Wn68Jp3k5yF4
  template:
    metadata:
      creationTimestamp: null
      name: my-app-secret
      namespace: default
